### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by hartwork** [cpptest/cpptest#13]
Before a release, the minimum needed more would be:
- [x] Understand and/or fix Doxygen issue #11 
- [x] Understand and/or fix memleak #2 
- [x] Extend the changelog for #9 and version 2.0.0
- [x] Fix references to SourceForge, i.e. update most to GitHub (related to #1)
- [x] Update http://cpptest.sourceforge.net/ with 2.0.0 docs
- [x] Upload 2.0.0 release archives to SourceForge, as well — https://sourceforge.net/projects/cpptest/files/cpptest/cpptest-2.0.0/

(based upon https://github.com/cpptest/cpptest/issues/9#issuecomment-451489827)
